apiVersion: v2
name: shunt
description: A merge queue for Forgejo and Gitea
type: application
version: 0.4.0
appVersion: 0.4.0
sources:
  - https://github.com/rbtr/shunt
maintainers:
  - name: rbtr
    url: https://github.com/rbtr
