apiVersion: v1
kind: Service
metadata:
  name: {{ include "shunt.fullname" . }}
  labels:
    {{- include "shunt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "shunt.selectorLabels" . | nindent 4 }}
  ports:
    - name: health
      port: {{ .Values.service.port }}
      targetPort: health
